ALTER TABLE "Order" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Order" ALTER COLUMN "updatedAt" DROP NOT NULL;
ALTER TABLE "OrderItem" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
